[request_definition]
r = role, resource, action

[policy_definition]
p = role, resource, action

[policy_effect]
e = some(where (p.eft == allow))

[matchers]
m = r.role == p.role && r.resource == p.resource && r.action == p.action
